server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
logging:
  file:
    path: "logs/"
indexing-settings:
  user_agent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
  referrer: "www.yandex.com"
  lemmaFrequency: 15
  snippetWords: 10
  sites:
  - url: https://lenta.ru
    name: Лента.ру
  - url: https://skillbox.ru
    name: Skillbox
  - url: https://www.playback.ru
    name: PlayBack.Ru

